"""Initial migration: users, patients, addresses tables

Revision ID: 2f5d70f06dca
Revises: 
Create Date: 2025-11-12 16:33:29.148471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5d70f06dca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_chat_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupons',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institutions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_specs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_coupons',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号（加密存储）'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='密码哈希'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='性别: male/female/unknown'),
    sa.Column('birth_date', sa.Date(), nullable=True, comment='出生日期'),
    sa.Column('wechat_openid', sa.String(length=100), nullable=True, comment='微信OpenID'),
    sa.Column('wechat_unionid', sa.String(length=100), nullable=True, comment='微信UnionID'),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True, comment='账户余额'),
    sa.Column('points', sa.Integer(), nullable=True, comment='积分'),
    sa.Column('member_level', sa.String(length=20), nullable=True, comment='会员等级'),
    sa.Column('total_orders', sa.Integer(), nullable=True, comment='总订单数'),
    sa.Column('total_spent', sa.Numeric(precision=10, scale=2), nullable=True, comment='总消费金额'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: active/disabled/blocked'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('wechat_openid')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_phone', ['phone'], unique=False)
        batch_op.create_index('idx_users_status', ['status'], unique=False)
        batch_op.create_index('idx_users_wechat_openid', ['wechat_openid'], unique=False)

    op.create_table('addresses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('contact_name', sa.String(length=50), nullable=False, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=20), nullable=False, comment='联系电话'),
    sa.Column('province', sa.String(length=50), nullable=False, comment='省份'),
    sa.Column('city', sa.String(length=50), nullable=False, comment='城市'),
    sa.Column('district', sa.String(length=50), nullable=False, comment='区/县'),
    sa.Column('detail_address', sa.String(length=255), nullable=False, comment='详细地址'),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='纬度'),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='经度'),
    sa.Column('address_type', sa.String(length=20), nullable=True, comment='地址类型: home/company/hospital/other'),
    sa.Column('label', sa.String(length=50), nullable=True, comment='自定义标签'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否默认地址'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.create_index('idx_addresses_user_id', ['user_id'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='姓名'),
    sa.Column('gender', sa.String(length=10), nullable=False, comment='性别'),
    sa.Column('birth_date', sa.Date(), nullable=True, comment='出生日期'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('id_card', sa.String(length=100), nullable=True, comment='身份证号（加密存储）'),
    sa.Column('relationship', sa.String(length=20), nullable=True, comment='与用户关系: self/parent/spouse/child/other'),
    sa.Column('medical_history', sa.Text(), nullable=True, comment='病史摘要'),
    sa.Column('allergies', sa.Text(), nullable=True, comment='过敏史'),
    sa.Column('special_needs', sa.Text(), nullable=True, comment='特殊需求'),
    sa.Column('insurance_type', sa.String(length=50), nullable=True, comment='医保类型'),
    sa.Column('insurance_number', sa.String(length=100), nullable=True, comment='医保卡号'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否默认就诊人'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index('idx_patients_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index('idx_patients_user_id')

    op.drop_table('patients')
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index('idx_addresses_user_id')

    op.drop_table('addresses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_wechat_openid')
        batch_op.drop_index('idx_users_status')
        batch_op.drop_index('idx_users_phone')

    op.drop_table('users')
    op.drop_table('user_coupons')
    op.drop_table('services')
    op.drop_table('service_specs')
    op.drop_table('reviews')
    op.drop_table('payments')
    op.drop_table('orders')
    op.drop_table('messages')
    op.drop_table('institutions')
    op.drop_table('coupons')
    op.drop_table('conversations')
    op.drop_table('companions')
    op.drop_table('ai_chat_history')
    op.drop_table('admin_users')
    op.drop_table('admin_logs')
    # ### end Alembic commands ###
