"""Initial migration

Revision ID: 5a3bd103ca13
Revises: 
Create Date: 2025-11-13 22:27:27.870430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3bd103ca13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_admin_logs')
    with op.batch_alter_table('admin_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('admin_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('_alembic_tmp_admin_logs',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('admin_id', sa.BIGINT(), nullable=False),
    sa.Column('admin_username', sa.VARCHAR(length=50), nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), nullable=False),
    sa.Column('module', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), nullable=True),
    sa.Column('request_method', sa.VARCHAR(length=10), nullable=True),
    sa.Column('request_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('request_data', sa.TEXT(), nullable=True),
    sa.Column('response_status', sa.INTEGER(), nullable=True),
    sa.Column('response_data', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
